
###################################### Navigation english ######################################

[[main]]
identifier = "motorhomes"
name = "Motorhomes"
weight = 1

  [[main]]
  identifier = "motorhomes_our_builds"
  parent = "motorhomes"
  name = "Our Builds"
  url = "our-builds/"
  weight = 1

  [[main]]
  identifier = "motorhomes_for_sale"
  parent = "motorhomes"
  name = "For Sale"
  url = "products/motorhome/"
  weight = 2

[[main]]
name = "Services"
url = "/#services"
weight = 2

[[main]]
identifier = "shop"
name = "Shop"
url = "products/"
weight = 3

  [[main]]
  identifier = "shop_wood-products"
  parent = "shop"
  name = "Wood Products"
  url = "products/wood-product/"
  weight = 1

[[main]]
identifier = "resources"
name = "Resources"
weight = 4

  [[main]]
  identifier = "blog"
  parent = "resources"
  name = "Blog"
  url = "https://www.epiclines.nz/blog/"
  weight = 1

  [[main]]
  identifier = "about"
  parent = "resources"
  name = "About"
  url = "https://www.epiclines.nz/about/"
  weight = 2

  [[main]]
  identifier = "contact"
  parent = "resources"
  name = "Contact"
  url = "https://www.epiclines.nz/contact/"
  weight = 3

  [[main]]
  identifier = "review"
  parent = "resources"
  name = "Testimonials"
  url = "/#testimonial"
  weight = 4

  # Todo: Implement https://www.uccmotorhomes.co.nz/review
  # [[main]]
  # identifier = "leave_review"
  # parent = "resources"
  # name = "Leave a Review"
  # url = "/#"
  # weight = 5

  [[main]]
  identifier = "terms_conditions"
  parent = "resources"
  name = "Terms & Conditions"
  url = "terms-conditions/"
  weight = 6


# add params.newTab = true to any menu item you want to be opened in a new tab.



# footer menu
[[footer]]
name = "Blog"
url = "https://www.epiclines.nz/blog/"
weight = 1

[[footer]]
name = "Contact"
url = "https://www.epiclines.nz/contact/"
weight = 2

[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 3

